[rospy.client][INFO] 2019-01-11 09:41:54,000: init_node, name[/rostopic_3884_1547206913926], pid[3884]
[xmlrpc][INFO] 2019-01-11 09:41:54,001: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-01-11 09:41:54,002: ROS Slave URI: [http://onboardpc:33821/]
[xmlrpc][INFO] 2019-01-11 09:41:54,001: Started XML-RPC server [http://onboardpc:33821/]
[rospy.impl.masterslave][INFO] 2019-01-11 09:41:54,002: _ready: http://onboardpc:33821/
[xmlrpc][INFO] 2019-01-11 09:41:54,007: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-01-11 09:41:54,008: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-01-11 09:41:54,102: registered with master
[rospy.rosout][INFO] 2019-01-11 09:41:54,103: initializing /rosout core topic
[rospy.rosout][INFO] 2019-01-11 09:41:54,106: connected to core topic /rosout
[rospy.simtime][INFO] 2019-01-11 09:41:54,107: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2019-01-11 09:41:54,180: topic[/rosarnl_node/amcl_pose] adding connection to [http://onboardpc:45179/], count 0
[rospy.internal][INFO] 2019-01-11 09:41:54,330: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-01-11 09:41:59,632: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-01-11 09:41:59,642: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-01-11 09:41:59,643: topic[/rosarnl_node/amcl_pose] removing connection to http://onboardpc:45179/
[rospy.internal][WARNING] 2019-01-11 09:41:59,645: Unknown error initiating TCP/IP socket to onboardpc:44673 (http://onboardpc:45179/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2019-01-11 09:41:59,645: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2019-01-11 09:41:59,645: signal-2
[rospy.core][INFO] 2019-01-11 09:41:59,753: signal_shutdown [atexit]
